
version: '3.7'

services:

  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432